baseURL: "https://unswnlp.github.io/" 
title: UNSW NLP
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: People
          url: people/
          weight: 2
        - name: Publications
          url: publications/
          weight: 3
        # - name: Resources
        #   url: resources/
        #   weight: 4
        # - name: Contact
        #   url: contact/
        #   weight: 5 
        - name: Location
          url: location/
          weight: 6

params:
    description: "Welcome to UNSW NLP group. This website contains recent news, publications, people and resources from the UNSW NLP Research Group."
    author: UNSW NLP
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["people","papers","resources","contact"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Welcome to the UNSW NLP Group!
          subtitle: |
            <p>The UNSW NLP Group broadly studies Foundational, Applied and Inclusive NLP. The group is headed by Dr. Aditya Joshi, a Lecturer in Computer Science and Engineering School at UNSW.</p>
            <br>
            <p>If you are interested in joining our group, please email <a href="mailto:aditya.joshi@unsw.edu.au" class=join-link>Aditya</a>.</p>

          imageUrl: "prof-pic.png"
          imageWidth: 260
          imageHeight: 300
          buttons:
            # - name: About Me
            #   url: /
            # - name: Papers
            #   url: papers/
            # - name: Resources
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: CV
            #   url: cv.pdf

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        # - name: Email
        #   url: mailto:d.srirag@unsw.edu.au
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=8dUrhxwAAAAJ
        # - name: GitHub
        #   url: https://github.com/dipankarsrirag
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/dipankarsrirag
        # - name: Bluesky
        #   url: https://bsky.app/profile/dipankarsrirag.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "UNSW NLP"
      icon: logo.png
      iconHeight: 24

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2